server:
  port: 8093

spring:
  application:
    name: ms-co2sensors-be

  jackson:
    default-property-inclusion: NON_NULL

  liquibase:
    change-log: classpath:liquibase/master.xml
    database-change-log-table: CO2_SENSOR_DATABASECHANGELOG
    database-change-log-lock-table: CO2_SENSOR_DATABASECHANGELOGLOCK
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /rest/management
      exposure:
        include: "prometheus,*"